from __future__ import annotations

STATUS_OK = "OK"
STATUS_RATE_LIMITED = "429"
STATUS_FAIL = "FAIL"
STATUS_MISSING = "MISSING"

MIN_MODEL_SAMPLES = 3
STABLE_OK_RATE_MIN = 0.75
STABLE_RATE_LIMITED_RATE_MAX = 0.25
UNSTABLE_FLIP_MIN = 2
UNSTABLE_RATE_LIMITED_RATE_MIN = 0.4
UNSTABLE_OK_RATE_MAX = 0.4
